name: /uufs/chpc.utah.edu/common/home/u1527341/miniconda3/envs/FMT
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - argcomplete=3.6.2=pyhd8ed1ab_0
  - arpack=3.9.1=nompi_hf03ea27_102
  - asttokens=3.0.0=pyhd8ed1ab_1
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - bioconductor-biobase=2.66.0=r44h3df3fcb_0
  - bioconductor-biocgenerics=0.52.0=r44hdfd78af_3
  - bioconductor-biocparallel=1.40.0=r44he5774e6_1
  - bioconductor-biomformat=1.34.0=r44hdfd78af_0
  - bioconductor-biostrings=2.74.0=r44h3df3fcb_1
  - bioconductor-data-packages=20250625=hdfd78af_0
  - bioconductor-delayedarray=0.32.0=r44h3df3fcb_1
  - bioconductor-deseq2=1.46.0=r44he5774e6_1
  - bioconductor-enhancedvolcano=1.24.0=r44hdfd78af_0
  - bioconductor-genomeinfodb=1.42.0=r44hdfd78af_2
  - bioconductor-genomeinfodbdata=1.2.13=r44hdfd78af_0
  - bioconductor-genomicranges=1.58.0=r44h3df3fcb_2
  - bioconductor-iranges=2.40.0=r44h3df3fcb_2
  - bioconductor-matrixgenerics=1.18.0=r44hdfd78af_0
  - bioconductor-multtest=2.62.0=r44h3df3fcb_1
  - bioconductor-phyloseq=1.50.0=r44hdfd78af_0
  - bioconductor-rhdf5=2.50.0=r44h77050f0_1
  - bioconductor-rhdf5filters=1.18.0=r44h77050f0_1
  - bioconductor-rhdf5lib=1.28.0=r44h15a9599_0
  - bioconductor-s4arrays=1.6.0=r44h3df3fcb_1
  - bioconductor-s4vectors=0.44.0=r44h3df3fcb_2
  - bioconductor-sparsearray=1.6.0=r44h3df3fcb_1
  - bioconductor-summarizedexperiment=1.36.0=r44hdfd78af_0
  - bioconductor-ucsc.utils=1.2.0=r44h9ee0642_1
  - bioconductor-xvector=0.46.0=r44h15a9599_2
  - bioconductor-zlibbioc=1.52.0=r44h3df3fcb_2
  - biom-format=2.1.16=py310ha75aee5_2
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - click=8.2.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py310h3788b33_0
  - curl=8.14.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.14=py310hf71b8c6_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.56.0=py310h89163eb_0
  - freetype=2.13.3=h48d6fc4_0
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=14.2.0=hdb7739f_2
  - gfortran_impl_linux-64=14.2.0=h0ee6e4a_2
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=h5888daf_0
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=14.2.0=h2ead766_2
  - h5py=3.14.0=nompi_py310hea1e86d_100
  - harfbuzz=11.2.1=h3beb420_0
  - hdf5=1.14.6=nompi_h2d575fe_101
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - jq=1.5=0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kernel-headers_linux-64=4.18.0=he073ed8_8
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - kraken-biom=1.2.0=pyh5e36f6f_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=14.2.0=h9c4974d_102
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.84.1=h2ff4ddf_0
  - libgomp=14.2.0=h767d61c_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.47=h943b412_0
  - libsanitizer=14.2.0=hed042b8_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=14.2.0=h9c4974d_102
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.7=h8d12d68_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.44.0=py310h1a6248f_1
  - make=4.4.1=hb9d3cd8_2
  - matplotlib-base=3.10.1=py310h68603db_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlopt=2.9.0=py310ha22d986_0
  - numba=0.61.0=py310h699fe88_1
  - numpy=2.1.3=py310hd6e36ab_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.2=h26f9b46_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py310h5eaa309_1
  - pandoc=3.7.0.2=ha770c72_0
  - pango=1.56.3=h9ac818e_1
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hc749103_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py310h7e6dc6c_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.46.4=h537e5f6_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py310ha75aee5_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - python=3.10.16=habfa6aa_2_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-igraph=0.11.8=py310h5996f03_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=6_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h89163eb_2
  - pyzmq=27.0.0=py310h71f11fc_0
  - qhull=2020.2=h434a139_5
  - r-abind=1.4_5=r44hc72bb7e_1006
  - r-ade4=1.7_23=r44hc2d650c_1
  - r-ape=5.8_1=r44hb79369c_0
  - r-askpass=1.2.1=r44h2b5f3a1_0
  - r-assertthat=0.2.1=r44hc72bb7e_5
  - r-backports=1.5.0=r44hb1dbf0f_1
  - r-base=4.4.3=h9c32bc2_0
  - r-base64enc=0.1_3=r44hb1dbf0f_1007
  - r-bazar=1.0.11=r44hc72bb7e_4
  - r-bh=1.87.0_1=r44hc72bb7e_0
  - r-bit=4.6.0=r44h2b5f3a1_0
  - r-bit64=4.6.0_1=r44h2b5f3a1_0
  - r-blob=1.2.4=r44hc72bb7e_2
  - r-boot=1.3_31=r44hc72bb7e_0
  - r-broom=1.0.9=r44hc72bb7e_0
  - r-bslib=0.9.0=r44hc72bb7e_0
  - r-cachem=1.1.0=r44hb1dbf0f_1
  - r-callr=3.7.6=r44hc72bb7e_1
  - r-car=3.1_3=r44hc72bb7e_0
  - r-cardata=3.0_5=r44hc72bb7e_3
  - r-caret=6.0_94=r44hdb488b9_2
  - r-cellranger=1.1.0=r44hc72bb7e_1007
  - r-class=7.3_23=r44h2b5f3a1_0
  - r-cli=3.6.5=r44h93ab643_0
  - r-clipr=0.8.0=r44hc72bb7e_3
  - r-clock=0.7.3=r44h93ab643_0
  - r-clue=0.3_66=r44h2b5f3a1_0
  - r-cluster=2.1.8.1=r44hb67ce94_0
  - r-codetools=0.2_20=r44hc72bb7e_1
  - r-colorspace=2.1_1=r44hdb488b9_0
  - r-conflicted=1.2.0=r44h785f33e_2
  - r-conquer=1.3.3=r44hb424bfc_4
  - r-corrplot=0.95=r44hc72bb7e_0
  - r-cowplot=1.2.0=r44hc72bb7e_1
  - r-cpp11=0.5.2=r44h785f33e_1
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-curl=6.2.2=r44h2700575_0
  - r-data.table=1.17.6=r44he23165d_0
  - r-dbi=1.2.3=r44hc72bb7e_1
  - r-dbplyr=2.5.0=r44hc72bb7e_1
  - r-deriv=4.2.0=r44hc72bb7e_0
  - r-diagram=1.6.5=r44ha770c72_3
  - r-digest=0.6.37=r44h0d4f4ea_0
  - r-dirmult=0.1.3_5=r44hc72bb7e_3
  - r-doby=4.7.0=r44hc72bb7e_0
  - r-dplyr=1.1.4=r44h0d4f4ea_1
  - r-dtplyr=1.3.1=r44hc72bb7e_2
  - r-e1071=1.7_16=r44h93ab643_0
  - r-ellipsis=0.3.2=r44hb1dbf0f_3
  - r-evaluate=1.0.4=r44hc72bb7e_0
  - r-fansi=1.0.6=r44hb1dbf0f_1
  - r-farver=2.1.2=r44ha18555a_1
  - r-fastmap=1.2.0=r44ha18555a_1
  - r-fbasics=4041.97=r44hdb488b9_0
  - r-fontawesome=0.5.3=r44hc72bb7e_0
  - r-forcats=1.0.0=r44hc72bb7e_2
  - r-foreach=1.5.2=r44hc72bb7e_3
  - r-formatr=1.14=r44hc72bb7e_2
  - r-formula=1.2_5=r44hc72bb7e_2
  - r-fs=1.6.6=r44h93ab643_0
  - r-futile.logger=1.4.3=r44hc72bb7e_1006
  - r-futile.options=1.0.1=r44hc72bb7e_1005
  - r-future=1.67.0=r44h785f33e_0
  - r-future.apply=1.20.0=r44hc72bb7e_0
  - r-gargle=1.5.2=r44h785f33e_1
  - r-gbrd=0.4.12=r44hc72bb7e_1
  - r-generics=0.1.4=r44hc72bb7e_0
  - r-ggplot2=3.5.2=r44hc72bb7e_0
  - r-ggrepel=0.9.6=r44h3697838_1
  - r-ggsignif=0.6.4=r44hc72bb7e_2
  - r-globals=0.18.0=r44hc72bb7e_0
  - r-glue=1.8.0=r44h2b5f3a1_0
  - r-googledrive=2.1.1=r44hc72bb7e_2
  - r-googlesheets4=1.1.1=r44h785f33e_2
  - r-gower=1.0.1=r44hb1dbf0f_2
  - r-gss=2.2_9=r44hd37a5e2_0
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-gunifrac=1.8=r44h0d4f4ea_1
  - r-hardhat=1.4.2=r44hc72bb7e_0
  - r-haven=2.5.4=r44h0d4f4ea_1
  - r-highr=0.11=r44hc72bb7e_1
  - r-hms=1.1.3=r44hc72bb7e_2
  - r-htmltools=0.5.8.1=r44ha18555a_1
  - r-httr=1.4.7=r44hc72bb7e_1
  - r-ids=1.0.1=r44hc72bb7e_4
  - r-igraph=2.0.3=r44h510f1ce_1
  - r-inline=0.3.21=r44hc72bb7e_0
  - r-ipred=0.9_15=r44hdb488b9_1
  - r-irdisplay=1.1=r44hd8ed1ab_3
  - r-irkernel=1.3.2=r44h785f33e_2
  - r-isoband=0.2.7=r44ha18555a_3
  - r-iterators=1.0.14=r44hc72bb7e_3
  - r-jquerylib=0.1.4=r44hc72bb7e_3
  - r-jsonlite=2.0.0=r44h2b5f3a1_0
  - r-kernsmooth=2.23_26=r44h8461fee_0
  - r-kimisc=1.0.0=r44hc72bb7e_0
  - r-knitr=1.50=r44hc72bb7e_0
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-lambda.r=1.2.4=r44hc72bb7e_4
  - r-lattice=0.22_7=r44h2b5f3a1_0
  - r-lava=1.8.1=r44hc72bb7e_0
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-listenv=0.9.1=r44hc72bb7e_1
  - r-lme4=1.1_37=r44h93ab643_0
  - r-lobstr=1.1.2=r44ha18555a_4
  - r-locfit=1.5_9.12=r44h2b5f3a1_0
  - r-lubridate=1.9.4=r44h2b5f3a1_0
  - r-magrittr=2.0.3=r44hb1dbf0f_3
  - r-mass=7.3_64=r44h2b5f3a1_0
  - r-matrix=1.7_3=r44h2ae2be5_0
  - r-matrixmodels=0.5_4=r44hc72bb7e_0
  - r-matrixstats=1.5.0=r44h2b5f3a1_0
  - r-memoise=2.0.1=r44hc72bb7e_3
  - r-mgcv=1.9_3=r44h2ae2be5_0
  - r-microbenchmark=1.5.0=r44h2b5f3a1_0
  - r-mime=0.13=r44h2b5f3a1_0
  - r-minqa=1.2.8=r44ha936806_0
  - r-modeest=2.4.0=r44hd8ed1ab_4
  - r-modelmetrics=1.2.2.2=r44h0d4f4ea_4
  - r-modelr=0.1.11=r44hc72bb7e_2
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-nlme=3.1_168=r44hb67ce94_0
  - r-nloptr=2.2.1=r44hb8c4c88_0
  - r-nnet=7.3_20=r44h2b5f3a1_0
  - r-numderiv=2016.8_1.1=r44hc72bb7e_6
  - r-openssl=2.3.3=r44he8289e2_0
  - r-parallelly=1.45.1=r44h54b55ab_0
  - r-pbdzmq=0.3_14=r44h549f438_0
  - r-pbkrtest=0.5.5=r44hc72bb7e_0
  - r-permute=0.9_8=r44hc72bb7e_0
  - r-pillar=1.11.0=r44hc72bb7e_0
  - r-pixmap=0.4_14=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-plyr=1.8.9=r44ha18555a_1
  - r-prettyunits=1.2.0=r44hc72bb7e_1
  - r-proc=1.19.0.1=r44h3697838_0
  - r-processx=3.8.6=r44h2b5f3a1_0
  - r-prodlim=2025.04.28=r44h93ab643_0
  - r-progress=1.2.3=r44hc72bb7e_1
  - r-progressr=0.15.1=r44hc72bb7e_0
  - r-proxy=0.4_27=r44hb1dbf0f_3
  - r-pryr=0.1.6=r44h0d4f4ea_2
  - r-ps=1.9.1=r44h2b5f3a1_0
  - r-purrr=1.1.0=r44h54b55ab_0
  - r-quantreg=6.00=r44h012206f_0
  - r-r6=2.6.1=r44hc72bb7e_0
  - r-ragg=1.4.0=r44hdcc764c_0
  - r-rappdirs=0.3.3=r44hb1dbf0f_3
  - r-rbibutils=2.3=r44h2b5f3a1_0
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rcpp=1.1.0=r44h93ab643_0
  - r-rcpparmadillo=14.4.2_1=r44hc2d650c_0
  - r-rcppeigen=0.3.4.0.2=r44hb79369c_0
  - r-rdpack=2.6.4=r44hc72bb7e_0
  - r-readr=2.1.5=r44h0d4f4ea_1
  - r-readxl=1.4.5=r44h328fee5_0
  - r-recipes=1.3.1=r44hc72bb7e_0
  - r-reformulas=0.4.1=r44hc72bb7e_0
  - r-rematch=2.0.0=r44hc72bb7e_1
  - r-rematch2=2.1.2=r44hc72bb7e_4
  - r-repr=1.1.7=r44h785f33e_1
  - r-reprex=2.1.1=r44hc72bb7e_1
  - r-reshape2=1.4.4=r44h0d4f4ea_4
  - r-rlang=1.1.6=r44h93ab643_0
  - r-rmarkdown=2.29=r44hc72bb7e_0
  - r-rmutil=1.1.10=r44hb67ce94_3
  - r-rpart=4.1.24=r44h2b5f3a1_0
  - r-rstatix=0.7.2=r44hc72bb7e_2
  - r-rstudioapi=0.17.1=r44hc72bb7e_0
  - r-rvest=1.0.4=r44hc72bb7e_1
  - r-sass=0.4.10=r44h93ab643_0
  - r-scales=1.4.0=r44hc72bb7e_0
  - r-selectr=0.4_2=r44hc72bb7e_4
  - r-shape=1.4.6.1=r44ha770c72_1
  - r-snow=0.4_4=r44hc72bb7e_3
  - r-sp=2.2_0=r44h2b5f3a1_0
  - r-sparsem=1.84_2=r44hc4980d5_0
  - r-sparsevctrs=0.3.4=r44h2b5f3a1_0
  - r-spatial=7.3_18=r44h2b5f3a1_0
  - r-squarem=2021.1=r44hc72bb7e_3
  - r-stable=1.1.6=r44hdb488b9_3
  - r-stabledist=0.7_2=r44ha770c72_0
  - r-statip=0.2.3=r44hdb488b9_4
  - r-statmod=1.5.0=r44ha36c22a_2
  - r-stringi=1.8.7=r44h3c328a7_0
  - r-stringr=1.5.1=r44h785f33e_1
  - r-survival=3.8_3=r44h2b5f3a1_0
  - r-sys=3.4.3=r44h2b5f3a1_0
  - r-systemfonts=1.2.3=r44h5c043a3_0
  - r-textshaping=1.0.1=r44h16f7c1a_0
  - r-tibble=3.3.0=r44h2b5f3a1_0
  - r-tidyr=1.3.1=r44h0d4f4ea_1
  - r-tidyselect=1.2.1=r44hc72bb7e_1
  - r-tidyverse=2.0.0=r44h785f33e_2
  - r-timechange=0.3.0=r44ha18555a_1
  - r-timedate=4041.110=r44hc72bb7e_0
  - r-timeseries=4041.111=r44hc72bb7e_0
  - r-tinytex=0.57=r44hc72bb7e_0
  - r-tzdb=0.5.0=r44h93ab643_0
  - r-utf8=1.2.6=r44h2b5f3a1_0
  - r-uuid=1.2_1=r44hdb488b9_0
  - r-vctrs=0.6.5=r44h0d4f4ea_1
  - r-vegan=2.7_1=r44h012206f_0
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-vroom=1.6.5=r44h0d4f4ea_1
  - r-withr=3.0.2=r44hc72bb7e_0
  - r-xfun=0.52=r44h93ab643_0
  - r-xml2=1.3.8=r44h1bb2df6_0
  - r-yaml=2.3.10=r44hdb488b9_0
  - readline=8.2=h8c095d6_2
  - scikit-learn=1.6.1=py310h27f47ee_0
  - scipy=1.15.2=py310h1d65ade_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sed=4.9=h6688a6e_0
  - setuptools=75.8.2=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py310hf462985_0
  - sysroot_linux-64=2.28=h4ee821c_8
  - taxonkit=0.20.0=h9ee0642_0
  - tbb=2022.1.0=h4ce085d_0
  - texttable=1.7.0=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8d826fa_7
  - toml=0.10.2=pyhd8ed1ab_1
  - tomlkit=0.13.3=pyha770c72_0
  - tornado=6.5.1=py310ha75aee5_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - umap-learn=0.5.7=py310hff52083_1
  - unicodedata2=16.0.0=py310ha75aee5_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xmltodict=0.14.2=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yq=3.4.3=pyhe01879c_2
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /uufs/chpc.utah.edu/common/home/u1527341/miniconda3/envs/FMT
